"""add focal_length to photos

Revision ID: 96ba7619e2a1
Revises: 936ae0bfe554
Create Date: 2026-03-27 17:06:03.591290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96ba7619e2a1'
down_revision: Union[str, Sequence[str], None] = '936ae0bfe554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('focal_length', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'focal_length')
    # ### end Alembic commands ###
